;;; autocrypt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from autocrypt.el

(autoload 'autocrypt-create-account "autocrypt" "\
Create a GPG key for Autocrypt." t)
(autoload 'autocrypt-mode "autocrypt" "\
Enable Autocrypt support in current buffer.

This is a minor mode.  If called interactively, toggle the
`Autocrypt mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `autocrypt-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "autocrypt" '("autocrypt-"))


;;; Generated autoloads from autocrypt-gnus.el

(autoload 'autocrypt-gnus--install "autocrypt-gnus" "\
Prepare autocrypt for Gnus.")
(register-definition-prefixes "autocrypt-gnus" '("autocrypt-gnus--"))


;;; Generated autoloads from autocrypt-message.el

(autoload 'autocrypt-message--install "autocrypt-message" "\
Prepare autocrypt for message buffers.")
(register-definition-prefixes "autocrypt-message" '("autocrypt-message--"))


;;; Generated autoloads from autocrypt-mu4e.el

(autoload 'autocrypt-mu4e--install "autocrypt-mu4e" "\
Install autocrypt hooks for mu4e.")
(register-definition-prefixes "autocrypt-mu4e" '("autocrypt-mu4e--"))


;;; Generated autoloads from autocrypt-rmail.el

(register-definition-prefixes "autocrypt-rmail" '("autocrypt-rmail--"))

;;; End of scraped data

(provide 'autocrypt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; autocrypt-autoloads.el ends here
